Classes and objects
liigaa/MySyllabus pull request #6
Opened 2022-08-06 14:12 UTC by liigaa

2022-08-07 18:38 UTC, ausmoons requested changes

2022-08-07 18:38 UTC, ausmoons commented on exercises/ClassesAndObjects/Account/Program.cs
> +            Account mattsAccount = new Account("Matt's account", 1000.00);
MattsAccount

2022-08-07 18:38 UTC, ausmoons commented on exercises/ClassesAndObjects/Account/Program.cs
> +            Account a = new Account("A", 100.00);
Tur kur ir new .. kaut kas, var likt var -> var a = new Account("A", 100.00);

2022-08-07 18:38 UTC, ausmoons commented on exercises/ClassesAndObjects/Tests/ITestpaper.cs
> +    public interface ITestpaper
Šī izskatās pēc klases, nevis interface. Interface būtu metodes

2022-08-07 18:38 UTC, ausmoons commented on exercises/ClassesAndObjects/Tests/Testpaper.cs
> +        public string ClassName { get; set; }
Šeit nevajag interface

2022-08-07 18:38 UTC, ausmoons commented on exercises/ClassesAndObjects/Tests/Testpaper.cs
> +        public string ClassName { get; set; }
IStudent ir pareizi, bet šis nē

2022-08-08 14:34 UTC, EdgarsSalmins commented on exercises/ClassesAndObjects/Tests/ITestpaper.cs
> +    public interface ITestpaper
vienīgais kas Te varbūt nav pareizi ir ka nevajadzētu atļaut setot vērtības... attiecīgi gan ClassName, MarkScheme, PassMark vajadzētu būt tikai get
pārējais manuprāt ir fine.

2022-08-09 20:00 UTC, ausmoons approved these changes

2022-08-10 05:48 UTC, merged