Polymorphism
liigaa/MySyllabus pull request #8
Opened 2022-08-17 09:39 UTC by liigaa

2022-08-19 17:54 UTC, ausmoons requested changes

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/Firm/Commission.cs
> +        public Commission(string eName, string eAddress, string ePhone, string socSecNumber, double rate, double commissionRate) : base(eName, eAddress, ePhone, socSecNumber, rate)
Lai nav viena gara rinda, labāk sākt jaunu rindu pirms ":"

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/Firm/Commission.cs
> +        public override string ToString()
Starp metodēm tukša rinda

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/Hierarchy/Mouse.cs
> +        public override void Eat(Food food)
Starp metodēm tukša rinda

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/Hierarchy/Program.cs
> +                    animals[animals.Count - 1].Eat((Food)Activator.CreateInstance(Type.GetType("Hierarchy." + input2[0]), int.Parse(input2[1])));
Tev atkārtojas kods.

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +                Amount = Amount.AddCoins(amount);
Amount.AddCoins(amount), bez "Amount =" neder?

2022-08-19 17:54 UTC, ausmoons commented on exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            Console.WriteLine("Not valid product number");
Šis atkārtojas vairākas reizes..labāk izveidot atsevišķu metodi

2022-08-20 07:00 UTC, liigaa commented on exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +                Amount = Amount.AddCoins(amount);
Šeit bez "Amount" nestrādā, jo Amount ir klases mainīgais, kam jāpiešķir vērtība

2022-08-20 08:35 UTC, ausmoons commented on exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +                Amount = Amount.AddCoins(amount);
Man uz datora strādāja un erroru nerādīja, bet ok

2022-08-20 08:36 UTC, ausmoons approved these changes

2022-08-20 15:38 UTC, merged